#!/usr/bin/env node
/**
 * generate-sw.mjs — generates dist/sw.js, a precaching service worker listing
 * every file in dist/. Runs as the final step of `npm run build`.
 * No dependencies: node:fs, node:path, node:crypto only. Do not add packages.
 *
 * Usage: node scripts/generate-sw.mjs [distDir]
 * (distDir defaults to the repo's dist/; the argument exists for build tooling
 * that needs to point at a copy.)
 */
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const distDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist')

if (!fs.existsSync(path.join(distDir, 'index.html'))) {
  console.error('generate-sw: dist/index.html not found — run `vite build` first.')
  process.exit(1)
}

/** Recursively list every file under dir; returns absolute paths. */
function walk(dir) {
  const files = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) files.push(...walk(full))
    else if (entry.isFile()) files.push(full)
  }
  return files
}

const entries = walk(distDir)
  .filter((file) => path.relative(distDir, file) !== 'sw.js') // never precache the worker itself
  .map((file) => {
    const rel = path.relative(distDir, file).split(path.sep).join('/')
    return {
      url: rel === 'index.html' ? '/' : '/' + rel, // the SPA shell caches under '/'
      size: fs.statSync(file).size,
    }
  })
  .sort((a, b) => (a.url < b.url ? -1 : 1))

const hash = crypto.createHash('sha256')
hash.update(entries.map((e) => `${e.url}:${e.size}`).join('\n'))
const VERSION = hash.digest('hex').slice(0, 12)

// One asset per line, two-space indent, double-quoted — the QA parity check
// (`grep -c '^  "' dist/sw.js`) depends on this exact formatting.
const assetLines = entries.map((e) => `  ${JSON.stringify(e.url)},`).join('\n')

const sw = `/* Generated by scripts/generate-sw.mjs — do not edit, do not commit. */
const CACHE = "mm-${VERSION}";
const ASSETS = [
${assetLines}
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    // SPA: every navigation is answered by the cached shell; React Router
    // resolves the actual route (/materials/golden-beads, etc.) client-side.
    event.respondWith(caches.match("/").then((cached) => cached || fetch(request)));
    return;
  }

  event.respondWith(
    caches
      .match(request)
      .then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            if (response.ok) {
              const clone = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, clone));
            }
            return response;
          })
      )
      .catch(() => caches.match("/"))
  );
});
`

fs.writeFileSync(path.join(distDir, 'sw.js'), sw)
console.log(`generate-sw: wrote dist/sw.js (cache mm-${VERSION}, ${entries.length} assets)`)
