#!/usr/bin/env node
/**
 * generate-sw.mjs — generates dist/sw.js, a precaching service worker listing
 * every file in dist/ the app itself uses. Runs as the final step of
 * `npm run build`, after prerender.mjs.
 * No dependencies: node:fs, node:path, node:crypto only. Do not add packages.
 *
 * Usage: node scripts/generate-sw.mjs [distDir]
 * (distDir defaults to the repo's dist/; the argument exists for build tooling
 * that needs to point at a copy.)
 */
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const distDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist')

if (!fs.existsSync(path.join(distDir, 'app-shell.html'))) {
  console.error('generate-sw: dist/app-shell.html not found — run `vite build` and scripts/prerender.mjs first.')
  process.exit(1)
}

/** Recursively list every file under dir; returns absolute paths. */
function walk(dir) {
  const files = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) files.push(...walk(full))
    else if (entry.isFile()) files.push(full)
  }
  return files
}

// Host config files that Cloudflare consumes and never serves. Precaching them
// would put 404s in the install list, and cache.addAll rejects as a unit — one
// bad entry means the worker never installs and the site loses offline support.
const NOT_ASSETS = new Set(['sw.js', '_headers', '_redirects', '.assetsignore'])

// Files for crawlers and link previews (PRD 21): the prerendered pages, the
// 404 page, sitemap.xml, robots.txt and the preview image. The app never
// requests them — every navigation is answered by the app shell — so
// precaching them would only add to every install.
const isForCrawlers = (rel) =>
  (rel.endsWith('.html') && rel !== 'app-shell.html') || ['sitemap.xml', 'robots.txt', 'og-image.png'].includes(rel)

// The app shell is Vite's template with no page in it (prerender.mjs saves
// it). It caches under /app-shell, the URL Cloudflare serves it at without a
// redirect: a navigation must never be answered with a redirected response.
const SHELL = '/app-shell'

const entries = walk(distDir)
  .map((file) => path.relative(distDir, file).split(path.sep).join('/'))
  .filter((rel) => !NOT_ASSETS.has(rel) && !isForCrawlers(rel))
  .map((rel) => ({
    url: rel === 'app-shell.html' ? SHELL : '/' + rel,
    size: fs.statSync(path.join(distDir, rel)).size,
  }))
  .sort((a, b) => (a.url < b.url ? -1 : 1))

// Self-hosted fonts (PRD 19) are precached like every other file above — they
// sit in public/fonts/, which Vite copies to dist/fonts/. Their combined size
// has a hard budget so a careless re-subset cannot bloat the first visit.
const FONT_BUDGET_BYTES = 200 * 1024
const fontBytes = entries
  .filter((e) => e.url.startsWith('/fonts/') && e.url.endsWith('.woff2'))
  .reduce((sum, e) => sum + e.size, 0)
const fontKB = (fontBytes / 1024).toFixed(1)
if (fontBytes > FONT_BUDGET_BYTES) {
  console.error(
    `generate-sw: fonts total ${fontKB} KB, over the ${FONT_BUDGET_BYTES / 1024} KB budget — re-run scripts/fonts/build-fonts.py.`,
  )
  process.exit(1)
}

const hash = crypto.createHash('sha256')
hash.update(entries.map((e) => `${e.url}:${e.size}`).join('\n'))
// The font files keep their names when build-fonts.py regenerates them and are
// served cache-first, so hash their bytes too: even a same-size change to a
// font reaches returning visitors through a new cache version.
for (const e of entries) {
  if (e.url.startsWith('/fonts/')) hash.update(fs.readFileSync(path.join(distDir, e.url.slice(1))))
}
const VERSION = hash.digest('hex').slice(0, 12)

// One asset per line, two-space indent, double-quoted — the QA parity check
// (`grep -c '^  "' dist/sw.js`) depends on this exact formatting.
const assetLines = entries.map((e) => `  ${JSON.stringify(e.url)},`).join('\n')

const sw = `/* Generated by scripts/generate-sw.mjs — do not edit, do not commit. */
const CACHE = "mm-${VERSION}";
const ASSETS = [
${assetLines}
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    // Every navigation is answered by the cached app shell; React Router
    // renders the actual route (/materials/golden-beads, etc.) client-side.
    event.respondWith(caches.match(${JSON.stringify(SHELL)}).then((cached) => cached || fetch(request)));
    return;
  }

  event.respondWith(
    caches
      .match(request)
      .then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            if (response.ok) {
              const clone = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, clone));
            }
            return response;
          })
      )
      .catch(() => caches.match(${JSON.stringify(SHELL)}))
  );
});
`

fs.writeFileSync(path.join(distDir, 'sw.js'), sw)
console.log(
  `generate-sw: wrote dist/sw.js (cache mm-${VERSION}, ${entries.length} assets; fonts ${fontKB} KB of ${FONT_BUDGET_BYTES / 1024} KB)`,
)
