import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './styles/tokens.css'
import './styles/global.css'
import './styles/print.css'
import './styles/materials.css'
import './styles/album.css'
import './styles/worksheets.css'
import './styles/guides.css'
import './styles/planner.css'
import './styles/presentation.css'
import './styles/booklet.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
)

// Offline support: precaching service worker, production build only
// (dist/sw.js is generated by scripts/generate-sw.mjs; it does not exist in dev).
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // Registration is best-effort: on http:// LAN origins (no secure context)
      // or older browsers the site simply stays online-only.
    })
  })
}
