import { StrictMode } from 'react'
import { createRoot, hydrateRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './styles/fonts.css'
import './styles/tokens.css'
import './styles/global.css'
import './styles/layout.css'
import './styles/contents.css'
import './styles/forms.css'
import './styles/print.css'
import './styles/materials.css'
import './styles/album.css'
import './styles/worksheets.css'
import './styles/guides.css'
import './styles/planner.css'
import './styles/presentation.css'

const container = document.getElementById('root')!
const app = (
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
)

// A prerendered page (scripts/prerender.mjs, PRD 21) names the path it was
// rendered for. Adopt its markup only on that path with no query string —
// queries drive presentation mode, worksheet settings, the planner and the
// age tabs, none of which were prerendered. Anything else (the service
// worker's empty app shell, the 404 page, a query) renders from scratch,
// replacing whatever the HTML carried.
if (container.dataset.prerendered === window.location.pathname && window.location.search === '') {
  hydrateRoot(container, app)
} else {
  createRoot(container).render(app)
}

// Offline support: precaching service worker, production build only
// (dist/sw.js is generated by scripts/generate-sw.mjs; it does not exist in dev).
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // Registration is best-effort: on http:// LAN origins (no secure context)
      // or older browsers the site simply stays online-only.
    })
  })
}
